(lambda (k)
  (lambda ()
    (((lambda (k)
        (k (lambda (kk sum.0)
             (lambda ()
               ((lambda (k)
                  (lambda ()
                    (((lambda (k)
                        (k (lambda (kk t.3)
                             (lambda ()
                               ((lambda (k)
                                  (lambda ()
                                    ((sum.0 (lambda (returnx) returnx))
                                     k
                                     (lambda (k) (k 10)))))
                                kk)))))
                      (lambda (returnx) returnx))
                     k
                     (set! sum.0
                           (lambda (k)
                             (k (lambda (kk n.1 total.2)
                                  (lambda ()
                                    ((lambda (k)
                                       ((lambda (k)
                                          (lambda ()
                                            (k (eq? (n.1 (lambda (returnx)
                                                           returnx))
                                                    ((lambda (k) (k 0))
                                                     (lambda (returnx)
                                                       returnx))))))
                                        (lambda (kif)
                                          (if kif
                                              (lambda () (total.2 k))
                                              (lambda ()
                                                ((lambda (k)
                                                   (lambda ()
                                                     ((sum.0
                                                       (lambda (returnx)
                                                         returnx))
                                                      k
                                                      (lambda (k)
                                                        (lambda ()
                                                          (k (add (n.1 (lambda (returnx)
                                                                         returnx))
                                                                  ((lambda (k)
                                                                     (k -1))
                                                                   (lambda (returnx)
                                                                     returnx))))))
                                                      (lambda (k)
                                                        (lambda ()
                                                          ((sum.0
                                                            (lambda (returnx)
                                                              returnx))
                                                           k
                                                           total.2
                                                           (lambda (k)
                                                             (k 1))))))))
                                                 k))))))
                                     kk)))))))))
                kk)))))
      (lambda (returnx) returnx))
     k
     (lambda (k) (lambda () (k (void)))))))
