(begin
  (let loop ([thunk ((lambda (k)
                       (lambda ()
                         ((lambda (k)
                            (k (lambda (k abc.0)
                                 (lambda ()
                                   ((lambda (k)
                                      (lambda ()
                                        (set! abc.0 (lambda (k) (k 42)))
                                        (k (void))))
                                     k)))))
                           (lambda (v)
                             (lambda ()
                               ((lambda (k) (k 0))
                                 (lambda (v0)
                                   (lambda ()
                                     (v k (lambda (kv) (kv v0)))))))))))
                      display)])
    (when (procedure? thunk) (loop (thunk))))
  (newline))

