(begin
  (let loop ([thunk ((lambda (k)
                       (lambda ()
                         ((lambda (k)
                            (k (lambda (k input.0)
                                 (lambda ()
                                   ((lambda (k)
                                      (lambda ()
                                        ((lambda (k)
                                           (k (lambda (k odd?.2 even?.1)
                                                (lambda ()
                                                  ((lambda (k)
                                                     (lambda ()
                                                       ((lambda (k)
                                                          (k (lambda (k
                                                                      t.5)
                                                               (lambda ()
                                                                 ((lambda (k)
                                                                    (lambda ()
                                                                      ((lambda (k)
                                                                         (k (lambda (k
                                                                                     t.6)
                                                                              (lambda ()
                                                                                ((lambda (k)
                                                                                   (lambda ()
                                                                                     (odd?.2
                                                                                       (lambda (v)
                                                                                         (lambda ()
                                                                                           (input.0
                                                                                             (lambda (v0)
                                                                                               (lambda ()
                                                                                                 (v k
                                                                                                    (lambda (kv)
                                                                                                      (kv v0)))))))))))
                                                                                  k)))))
                                                                        (lambda (v)
                                                                          (lambda ()
                                                                            ((lambda (k)
                                                                               (lambda ()
                                                                                 (set! even?.1
                                                                                   (lambda (k)
                                                                                     (k (lambda (k
                                                                                                 x.3)
                                                                                          (lambda ()
                                                                                            ((lambda (k)
                                                                                               ((lambda (k)
                                                                                                  (lambda ()
                                                                                                    (x.3 (lambda (v0)
                                                                                                           (lambda ()
                                                                                                             ((lambda (k)
                                                                                                                (k 0))
                                                                                                               (lambda (v1)
                                                                                                                 (k (eq? v0
                                                                                                                         v1)))))))))
                                                                                                 (lambda (kif)
                                                                                                   (if kif
                                                                                                       (lambda ()
                                                                                                         ((lambda (k)
                                                                                                            (k 1))
                                                                                                           k))
                                                                                                       (lambda ()
                                                                                                         ((lambda (k)
                                                                                                            (lambda ()
                                                                                                              (odd?.2
                                                                                                                (lambda (v)
                                                                                                                  (lambda ()
                                                                                                                    ((lambda (k)
                                                                                                                       (lambda ()
                                                                                                                         (x.3 (lambda (v0)
                                                                                                                                (lambda ()
                                                                                                                                  ((lambda (k)
                                                                                                                                     (k -1))
                                                                                                                                    (lambda (v1)
                                                                                                                                      (k (add v0
                                                                                                                                              v1)))))))))
                                                                                                                      (lambda (v0)
                                                                                                                        (lambda ()
                                                                                                                          (v k
                                                                                                                             (lambda (kv)
                                                                                                                               (kv v0)))))))))))
                                                                                                           k))))))
                                                                                              k))))))
                                                                                 (k (void))))
                                                                              (lambda (v0)
                                                                                (lambda ()
                                                                                  (v k
                                                                                     (lambda (kv)
                                                                                       (kv v0)))))))))))
                                                                   k)))))
                                                         (lambda (v)
                                                           (lambda ()
                                                             ((lambda (k)
                                                                (lambda ()
                                                                  (set! odd?.2
                                                                    (lambda (k)
                                                                      (k (lambda (k
                                                                                  x.4)
                                                                           (lambda ()
                                                                             ((lambda (k)
                                                                                ((lambda (k)
                                                                                   (lambda ()
                                                                                     (x.4 (lambda (v0)
                                                                                            (lambda ()
                                                                                              ((lambda (k)
                                                                                                 (k 0))
                                                                                                (lambda (v1)
                                                                                                  (k (eq? v0
                                                                                                          v1)))))))))
                                                                                  (lambda (kif)
                                                                                    (if kif
                                                                                        (lambda ()
                                                                                          ((lambda (k)
                                                                                             (k 0))
                                                                                            k))
                                                                                        (lambda ()
                                                                                          ((lambda (k)
                                                                                             (lambda ()
                                                                                               (even?.1
                                                                                                 (lambda (v)
                                                                                                   (lambda ()
                                                                                                     ((lambda (k)
                                                                                                        (lambda ()
                                                                                                          (x.4 (lambda (v0)
                                                                                                                 (lambda ()
                                                                                                                   ((lambda (k)
                                                                                                                      (k -1))
                                                                                                                     (lambda (v1)
                                                                                                                       (k (add v0
                                                                                                                               v1)))))))))
                                                                                                       (lambda (v0)
                                                                                                         (lambda ()
                                                                                                           (v k
                                                                                                              (lambda (kv)
                                                                                                                (kv v0)))))))))))
                                                                                            k))))))
                                                                               k))))))
                                                                  (k (void))))
                                                               (lambda (v0)
                                                                 (lambda ()
                                                                   (v k
                                                                      (lambda (kv)
                                                                        (kv v0)))))))))))
                                                    k)))))
                                          (lambda (v)
                                            (lambda ()
                                              ((void)
                                                (lambda (v0)
                                                  (lambda ()
                                                    ((void)
                                                      (lambda (v1)
                                                        (lambda ()
                                                          (v k
                                                             (lambda (kv)
                                                               (kv v0))
                                                             (lambda (kv)
                                                               (kv v1))))))))))))))
                                     k)))))
                           (lambda (v)
                             (lambda ()
                               ((lambda (k) (k 42))
                                 (lambda (v0)
                                   (lambda ()
                                     (v k (lambda (kv) (kv v0)))))))))))
                      display)])
    (when (procedure? thunk) (loop (thunk))))
  (newline))

