(begin
  (let loop ([thunk ((lambda (k)
                       (lambda ()
                         ((lambda (k)
                            (k (lambda (k abc.1 def.0)
                                 (lambda ()
                                   ((lambda (k)
                                      (lambda ()
                                        ((lambda (k)
                                           (k (lambda (k x.2)
                                                (lambda ()
                                                  ((lambda (k)
                                                     (lambda ()
                                                       (x.2 (lambda (v0)
                                                              (lambda ()
                                                                ((lambda (k)
                                                                   (k -1))
                                                                  (lambda (v1)
                                                                    (k (add v0
                                                                            v1)))))))))
                                                    k)))))
                                          (lambda (v)
                                            (lambda ()
                                              ((lambda (k)
                                                 (lambda ()
                                                   (abc.1
                                                     (lambda (v0)
                                                       (lambda ()
                                                         ((lambda (k)
                                                            (lambda ()
                                                              (def.0
                                                                (lambda (v0)
                                                                  (lambda ()
                                                                    ((lambda (k)
                                                                       (k 100))
                                                                      (lambda (v1)
                                                                        (k (times
                                                                             v0
                                                                             v1)))))))))
                                                           (lambda (v1)
                                                             (k (add v0
                                                                     v1)))))))))
                                                (lambda (v0)
                                                  (lambda ()
                                                    (v k
                                                       (lambda (kv)
                                                         (kv v0)))))))))))
                                     k)))))
                           (lambda (v)
                             (lambda ()
                               ((lambda (k) (k 42))
                                 (lambda (v0)
                                   (lambda ()
                                     ((lambda (k) (k 101))
                                       (lambda (v1)
                                         (lambda ()
                                           (v k
                                              (lambda (kv) (kv v0))
                                              (lambda (kv)
                                                (kv v1))))))))))))))
                      display)])
    (when (procedure? thunk) (loop (thunk))))
  (newline))

