(begin
  (let loop ([thunk ((lambda (k)
                       (lambda ()
                         ((lambda (k)
                            (k (lambda (k fact.0)
                                 (lambda ()
                                   ((lambda (k)
                                      (lambda ()
                                        ((lambda (k)
                                           (k (lambda (k t.3)
                                                (lambda ()
                                                  ((lambda (k)
                                                     (lambda ()
                                                       (fact.0
                                                         (lambda (v)
                                                           (lambda ()
                                                             ((lambda (k)
                                                                (k 100))
                                                               (lambda (v0)
                                                                 (lambda ()
                                                                   ((lambda (k)
                                                                      (k 1))
                                                                     (lambda (v1)
                                                                       (lambda ()
                                                                         (v k
                                                                            (lambda (kv)
                                                                              (kv v0))
                                                                            (lambda (kv)
                                                                              (kv v1))))))))))))))
                                                    k)))))
                                          (lambda (v)
                                            (lambda ()
                                              ((lambda (k)
                                                 (lambda ()
                                                   (set! fact.0
                                                     (lambda (k)
                                                       (k (lambda (k n.1
                                                                   total.2)
                                                            (lambda ()
                                                              ((lambda (k)
                                                                 ((lambda (k)
                                                                    (lambda ()
                                                                      (n.1 (lambda (v0)
                                                                             (lambda ()
                                                                               ((lambda (k)
                                                                                  (k 0))
                                                                                 (lambda (v1)
                                                                                   (k (eq? v0
                                                                                           v1)))))))))
                                                                   (lambda (kif)
                                                                     (if kif
                                                                         (lambda ()
                                                                           (total.2
                                                                             k))
                                                                         (lambda ()
                                                                           ((lambda (k)
                                                                              (lambda ()
                                                                                (fact.0
                                                                                  (lambda (v)
                                                                                    (lambda ()
                                                                                      ((lambda (k)
                                                                                         (lambda ()
                                                                                           (n.1 (lambda (v0)
                                                                                                  (lambda ()
                                                                                                    ((lambda (k)
                                                                                                       (k -1))
                                                                                                      (lambda (v1)
                                                                                                        (k (add v0
                                                                                                                v1)))))))))
                                                                                        (lambda (v0)
                                                                                          (lambda ()
                                                                                            ((lambda (k)
                                                                                               (lambda ()
                                                                                                 (total.2
                                                                                                   (lambda (v0)
                                                                                                     (lambda ()
                                                                                                       (n.1 (lambda (v1)
                                                                                                              (k (times
                                                                                                                   v0
                                                                                                                   v1)))))))))
                                                                                              (lambda (v1)
                                                                                                (lambda ()
                                                                                                  (v k
                                                                                                     (lambda (kv)
                                                                                                       (kv v0))
                                                                                                     (lambda (kv)
                                                                                                       (kv v1))))))))))))))
                                                                             k))))))
                                                                k))))))
                                                   (k (void))))
                                                (lambda (v0)
                                                  (lambda ()
                                                    (v k
                                                       (lambda (kv)
                                                         (kv v0)))))))))))
                                     k)))))
                           (lambda (v)
                             (lambda ()
                               ((void)
                                 (lambda (v0)
                                   (lambda ()
                                     (v k (lambda (kv) (kv v0)))))))))))
                      display)])
    (when (procedure? thunk) (loop (thunk))))
  (newline))

